// File author is Ítalo Lima Marconato Matias
//
// Created on January 18 of 2020, at 12:36 BRT
// Last edited on January 20 of 2020, at 11:21 BRT

#ifndef __CHICAGO_STATUS_H__
#define __CHICAGO_STATUS_H__

#include <chicago/types.h>

#define STATUS_INVALID_SYSCALL -1
#define STATUS_SUCCESS 0
#define STATUS_INVALID_ARG 1
#define STATUS_OUT_OF_MEMORY 2
#define STATUS_MAP_ERROR 3
#define STATUS_UNMAP_ERROR 4
#define STATUS_NOT_MAPPED 5
#define STATUS_ALREADY_MAPPED 6
#define STATUS_ALREADY_KILLED 7
#define STATUS_FILE_DOESNT_EXISTS 8
#define STATUS_FILE_ALREADY_EXISTS 9
#define STATUS_NOT_DIR 10
#define STATUS_NOT_FILE 11
#define STATUS_NOT_MOUNTED 12
#define STATUS_CANT_READ 13
#define STATUS_CANT_WRITE 14
#define STATUS_CANT_CONTROL 15
#define STATUS_MOUNT_FAILED 16
#define STATUS_UMOUNT_FAILED 17
#define STATUS_OPEN_FAILED 18
#define STATUS_READ_FAILED 19
#define STATUS_WRITE_FAILED 20
#define STATUS_CREATE_FAILED 21
#define STATUS_CONTROL_FAILED 22
#define STATUS_INVALID_CONTROL_CMD 23
#define STATUS_END_OF_FILE 24
#define STATUS_PORT_DOESNT_EXISTS 25
#define STATUS_PORT_ALREADY_EXISTS 26
#define STATUS_NOT_OWNER 27
#define STATUS_WRONG_HANDLE 28
#define STATUS_SHM_DOESNT_EXISTS 29
#define STATUS_TRYLOCK_FAILED 30

typedef IntPtr Status, *PStatus;

#endif		// __CHICAGO_STATUS_H__
